const products = [
    {
      id: 0,
      name: "Iphone 11",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Iphone",
      price: 2999.99,
      image: "./images/iphone-11.jpeg",
      sale: true,
      saleAmount: 200,
    },
    {
      id: 1,
      name: "Iphone 13",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Iphone",
      price: 5200.5,
      image: "./images/iphone-13.jpeg",
    },
    {
      id: 2,
      name: "Iphone 12",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Iphone",
      price: 4444.44,
      image: "./images/Iphone-12.jpeg",
      sale: true,
      saleAmount: 451,
    },
    {
      id: 3,
      name: "Huawei p50 pro",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Huawei",
      price: 1330,
      image: "./images/Huawei-2.jpeg",
    },
    {
      id: 4,
      name: "Huawei p20 lite",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Huawei",
      price: 2250,
      image: "./images/Huawei-1.jpeg",
    },
    {
      id: 5,
      name: "Nokia c300",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Nokia",
      price: 950,
      image: "./images/Nokia.jpeg",
      sale: true,
      saleAmount: 250,
    },
    {
      id: 6,
      name: "Nokia n70",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Nokia",
      price: 690,
      image: "./images/Nokia-2.jpeg",
    },
    {
      id: 7,
      name: "Samsung a53",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Samsung",
      price: 1440,
      image: "./images/Samsung-a53.jpeg",
    },
    {
      id: 8,
      name: "Samsung s20",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Samsung",
      price: 2620.2,
      image: "./images/Samsung-s20.jpeg",
      sale: true,
      saleAmount: 300,
    },
    {
      id: 9,
      name: "Samsung s22",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Samsung",
      price: 3399.99,
      image: "./images/Samsung-s22.jpeg",
    },
    {
        id: 10,
        name: "Motorola G31",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        category: "Motorola",
        price: 3399.99,
        image: "./images/Motorola-1.jpeg",
      }
  ];